In [33]:
from IPython.display import clear_output
import numpy as np
import matplotlib.pyplot as plt
import pandas
import math
import pydot
import graphviz
import tensorflow as tf
from pandas import Series , DataFrame, Panel
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Activation
from keras import metrics
import random
from IPython.display import SVG
from keras.utils.vis_utils import model_to_dot
from keras import backend as K
import time
from keras.layers import Dropout
import random
from keras.utils.np_utils import to_categorical
import math
np.random.seed(10)

In [34]:
def dict(letter):
    dict = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
    return dict.index(letter)
def undict(number):
    dict = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
    return dict[number]

In [35]:
def cov(str):
    output = []
    for i in str:
        output.append(dict(i))
    return output

In [36]:
def en(lst):
    output = []
    for i in range(0,len(lst)):
        if i == 0:
            output.append(lst[1])
        elif i == len(lst)-1:
            output.append(lst[-2])
        else:
            output.append((lst[i-1]+lst[i+1])%26)
    return output
            
        
        
   

In [37]:
def de(lst):
    output = []
    for i in lst:
        output.append(undict(i))
        
    return output

In [38]:
cov("salmon")

[18, 0, 11, 12, 14, 13]

In [39]:
en(cov("salmon"))

[0, 3, 12, 25, 25, 14]

In [40]:
#GENERATE DATASET
X = []
Y = []
for i in range(1,5000):
    data = random.sample(range(26), 4)
    Y.append(data)
    X.append(en(data))
X = np.array(X)
Y = np.array(Y)    


In [41]:
X[1]

array([ 0, 21,  1, 19])

In [42]:
Y[1]

array([ 2,  0, 19,  1])

In [43]:
X.shape

(4999, 4)

In [44]:
Y.shape

(4999, 4)

In [45]:
model = Sequential()
model.add(Dense(4,input_dim=X.shape[1],activation= 'relu'))
for i in range(1,3):
    model.add(Dense(256,activation='relu'))
    model.add(Dropout(0.2))
model.add(Dense(Y.shape[1]))
model.compile(loss= "MSE",optimizer='adam',metrics=['accuracy'])


startime= time.time()
history = model.fit(X,Y,epochs= 1000,batch_size = 50,verbose = 2, validation_split= 0.2,)
endtime = time.time()
print("time:")
print(endtime-startime)



Train on 3999 samples, validate on 1000 samples
Epoch 1/1000
0s - loss: 59.7905 - acc: 0.4534 - val_loss: 42.2692 - val_acc: 0.5050
Epoch 2/1000
0s - loss: 43.8666 - acc: 0.4976 - val_loss: 39.1013 - val_acc: 0.5110
Epoch 3/1000
0s - loss: 40.4782 - acc: 0.5031 - val_loss: 36.2451 - val_acc: 0.5240
Epoch 4/1000
0s - loss: 37.8905 - acc: 0.5236 - val_loss: 33.4422 - val_acc: 0.5300
Epoch 5/1000
0s - loss: 34.9073 - acc: 0.5421 - val_loss: 30.5212 - val_acc: 0.5860
Epoch 6/1000
0s - loss: 32.1372 - acc: 0.5731 - val_loss: 28.6234 - val_acc: 0.5920
Epoch 7/1000
0s - loss: 30.8531 - acc: 0.5859 - val_loss: 28.3519 - val_acc: 0.6160
Epoch 8/1000
0s - loss: 29.1625 - acc: 0.5964 - val_loss: 26.2381 - val_acc: 0.6230
Epoch 9/1000
0s - loss: 27.7080 - acc: 0.6094 - val_loss: 25.5682 - val_acc: 0.6370
Epoch 10/1000
0s - loss: 26.4834 - acc: 0.6219 - val_loss: 23.0284 - val_acc: 0.6280
Epoch 11/1000
0s - loss: 24.9638 - acc: 0.6407 - val_loss: 21.9024 - val_acc: 0.6630
Epoch 12/1000
0s - loss: 2

In [46]:
Test = np.array([en(cov("food"))])

In [47]:
np.round(model.predict(Test))

array([[  5.,  14.,  14.,   3.]], dtype=float32)

In [48]:
(cov("food"))

[5, 14, 14, 3]